# Generated by Django 4.1.5 on 2023-01-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_by',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
